#!/bin/bash

# Check if at least one argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 [build] [run]"
    exit 1
fi

# Build step
if [[ "$@" == *"build"* ]]; then
    echo "Building image..."
    cd tot-mcp-em/ || { echo "Directory 'tot-mcp-em' not found."; exit 1; }
    docker build --no-cache -t tot-mcp-em:local .
    cd .. # Return to original directory
fi

# Run step
if [[ "$@" == *"run"* ]]; then
    echo "Removing existing container..."
    docker rm -f tot-mcp-em || true
    
    echo "Running container..."
    docker run -d \
	-e MCP_LOG_LEVEL=debug \
  	-e MCP_DEBUG_GRAPHQL=1 \
        --restart unless-stopped \
        --name tot-mcp-em \
        -p 40443:40443 \
        -v /usr/local/mcp/data:/data \
        tot-mcp-em:local
fi
